allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://jitpack.io"
            credentials { username "jp_k2i539pgktqmks7mqfjfnaaivp" }
        }
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
