# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'Runner' do
  source 'https://github.com/CocoaPods/Specs'
  source 'https://github.com/Asli-RI/asliri-podspecs'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo1
  pod 'asli-ocr', '2.0.6'

end
